export default [
  `Intrigue is when one character keeps a dangerous or malevolent secret from another. Write a scene that creates intrigue.`,
  `You can raise the stakes by putting something a character cares about at risk. Write a scene that raises the stakes.`,
  `Dramatic irony is when the reader knows something important that a character does not. Write a scene that creates dramatic irony.`,
  `Suspense is when the reader wonders anxiously what will happen next. Write a scene where the outcome of a decision, a natural event, or an interaction is urgent and uncertain.`,
  `Plots often weave together moments of action and moments of reflection. Determine whether your last scene involved more action or more reflection, then write a scene that does the opposite.`,
  `A character's first attempt to solve a problem is rarely successful. Write a scene where someone tries and fails to solve a problem.`,
  `Perverseness is when a character willfully makes the wrong choice or makes things worse for themself. Write a scene where a character does something perverse.`,
  `Most plots are a series of structured surprises. Write a scene that surprises the reader.`,
  `You can build tension by moving up your timeline. Write a scene where something happens much sooner than expected.`,
  `Characters' relationships with each other often evolve and improve over the course of a novel. Write a scene where one character misjudges another (too harshly or too generously).`,
  `Write a scene where a character acts on a false assumption.`,
  `Write a scene where two characters disagree, but neither of them is necessarily wrong.`,
  `Write a scene where a character speculates about what another character is doing.`,
  `Write a scene where a character speculates about another character's motives.`,
  `Write a scene where a character makes an incorrect prediction.`,
  `An epiphany is when a character has a sudden, sweeping realization about themself or their situation. Write a scene where someone has an epiphany.`,
  `Write a scene that is influenced by events the reader doesn't know about yet. That is, something important has happened offstage, and all the reader can see are the consequences.`,
  `Write a scene where something makes a character very uncomfortable.`,
  `Write a scene where a character loses their temper.`,
  `Write a scene where a character's hidden motives are revealed.`,
  `Write a scene where a character shows up unexpectedly.`,
  `Characters are more lifelike when they're a little unpredictable. Write a scene where a character does something that surprises even them.`,
  `Write a scene where one character gives another some bad advice.`,
  `Write a scene where two or more characters have a conversation and one of them completely misunderstands it.`
]
