export default [
  'Intrigue is when one character keeps a dangerous or malevolent secret from another. Write a scene that creates intrigue.',
  'Write a scene that raises the stakes by putting something a character cares about at risk.',
  'Write a scene where the reader finds out something important that one of the characters doesn\'t yet know.',
  'Suspense is when the reader wonders anxiously what will happen next. Write a scene where the outcome of a decision, a natural event, or an interaction is urgent and uncertain.',
  'Plots often weave together moments of action and moments of reflection. Determine whether your last scene involved more action or more reflection, then write a scene that does the opposite.',
  'A character\'s first attempt to solve a problem is rarely successful. Write a scene where someone tries and fails to solve a problem.',
  'Perverseness is when a character willfully makes the wrong choice or makes things worse for themself. Write a scene where a character does something perverse.',
  'Write a scene that sets up the reader to expect a certain outcome, but then the opposite happens.',
  'Write a scene where something happens much sooner than expected.',
  'Characters\' relationships with each other often change over the course of a novel. Write a scene where one character misjudges another (too harshly or too generously).',
  'Write a scene where a character acts on a false assumption.',
  'Write a scene where two characters disagree, but neither of them is necessarily wrong.',
  'Write a scene where a character speculates about what another character is doing.',
  'Write a scene where a character speculates about another character\'s motives.',
  'Write a scene where a character makes an incorrect prediction.',
  'An epiphany is when a character has a sudden, sweeping realization about themself or their situation. Write a scene where someone has an epiphany.',
  'Write a scene that is influenced by events the reader doesn\'t know about yet. That is, something important has happened offstage, and all the reader can see are the consequences.',
  'Write a scene where something makes a character very uncomfortable.',
  'Write a scene where a character loses their temper.',
  'Write a scene where a character\'s hidden motives are revealed.',
  'Write a scene where a character shows up unexpectedly.',
  'Characters are more lifelike when they\'re a little unpredictable. Write a scene where a character does something that surprises another character or even themself.',
  'Write a scene where one character gives another some bad advice.',
  'Write a scene where two or more characters have a conversation and one of them completely misunderstands it.',
  'Write a scene where a character\'s loyalties are tested.',
  'Write a scene where one character tries to convince another to change sides in a conflict.',
  'Write a scene where a character accidentally discovers something about another character that could change their relationship.',
  'Write a scene where a character faces the consequences of a decision they thought was far behind them.',
  'Write a scene where one character\'s trust in another is broken.',
  'Write a scene where a character gets lost and ends up somewhere interesting.',
  'Write a scene where something potentially helpful comes from an untrustworthy source.',
  'Write a scene where one character eavesdrops on another\'s conversation.',
  'Write a scene where one character apologizes to another.',
  'Write a scene where a character gives up, but something happens to motivate them to keep trying.',
  'Write a scene where a character makes a big mistake and assumes all is lost.',
  'Write a scene where one character interrogates another.',
  'Write a scene where a character is forced to defend a lie they told earlier.',
  'Write a scene where one character falsely accuses another of a crime or misdeed.',
  'Write a scene where a character\'s reputation has preceded them.',
  'Write a scene where a character is forced to choose between two things they care deeply about.',
  'Write a scene where a character is asked to trust a complete stranger.',
  'Write a scene where a character is forced to invent a story to explain their presence somewhere.',
  'Write a scene where two characters at odds with each other are forced to work together.',
]
