export default [
  'A blind person is passing through.',
  'A person in a wheelchair or on crutches is passing through.',
  'A poet is using the place as inspiration.',
  'A deadly battle is taking place.',
  'A local church is having a picnic.',
  'An activist group is protesting.',
  'Two people on horseback are riding at a leisurely pace.',
  'Someone is hiding from a terrifying creature.',
  'A search party is looking for a missing person.',
  'Two lovers are meeting in secret.',
  'A fugitive from the law is trying to pass through without being noticed.',
  'A politician is making a speech.',
  'A fire is growing out of control.',
  'An animal is looking for a comfortable place to give birth.',
  'A homeless person is looking for something to eat.',
  'A group of children is playing a risky game.',
  'Someone is looking for a quiet place to cry.',
  'A lost traveler is trying to find their way.',
  'A mother is trying to shelter her infant from a storm.',
  'A clumsy jogger is passing through.',
  'A group of performers is trying to draw an audience.',
  'A beloved friend is speaking their last words.',
  'A hunter is quietly stalking their prey.',
  'A grandparent is reminiscing about how things used to be.',
  'An officer of the law is looking for a criminal.',
  'An unruly crowd is gathering.'
]
